.TH lintool "1" "March 2002" "gentoolkit 0.1.3" 
.SH NAME
lintool \- manual page for the lintool program, a program that checks the 
santity of ebuild scripts.
.SH SYNOPSIS
.B lintool
\fI<switches>\fR \fIebuilds...\fR
.SH DESCRIPTION
Lintool checks if a set of
.I ebuilds
conforms to the ebuild style guide. This is not
(yet) an exhaustive test, so your ebuild might be broken even if lintool 
thinks it's okay.
.PP
.SH OPTIONS 
.TP
\fB--no-summary\fI
Turn off total summary for all tests run on all ebuilds.
.TP
\fB--show-separate\fI
Show short summary of tests for each ebuild checked.
.TP
\fB--show-details\fI
Show full details of tests for each ebuild checked
.TP
\fB--tests=test1,test2,..\fI
Run only the tests specified to this option. Default is to run all
tests. One can turn off a particular test by pretending it with minus (e.g.
.I --tests=-TestUseFlags,-TestSpaces
). A list of tests can be obtained from
.I --list-tests
.TP
\fB--list-tests\fI
List available tests.
.SH AUTHORS
Karl Trygve Kalleberg <karltk@gentoo.org>, 2002
.SH "SEE ALSO"
ebuild(5) 
.TP
The \fI/usr/sbin/lintool\fR script. 

