.TH pkg-clean "1" "Nov 2003" "gentoolkit"
.SH NAME
pkg-clean \- Gentoo: Clean obsolete packages
.SH SYNOPSIS
.B pkg-clean
.SH BUGS
This tool does not yet have a man page. Feel free to submit a bug about it to
http://bugs.gentoo.org
.SH AUTHORS
This informative man page was written by Karl Trygve Kalleberg 
<karltk@gentoo.org>.

