.TH pkg\-clean "1" "Nov 2003" "gentoolkit"
.SH NAME
pkg\-clean \- Gentoo: Clean obsolete packages
.SH SYNOPSIS
.B pkg\-clean
.SH BUGS
This tool is obsolete, as of gentoolkit 0.2.0.
Use 'emerge clean' or 'emerge depclean' (with caution; read the man page) 
instead.

.SH SEE ALSO
.BR emerge(1)
.br
.BR /usr/sbin/pkg\-clean

.SH AUTHORS
This informative man page was written by Karl Trygve Kalleberg 
<karltk@gentoo.org> and expanded by Katerina Barone\-Adesi 
<katerinab@gmail.com>.

