.TH "qpkg" "1" "1.6" "gentoolkit 0.1.11-r1" ""
.SH "NAME"
qpkg \- the "query package" tool for Gentoo Linux
.SH "SYNOPSIS"
.LP 
.B qpkg\fR	[\fIoptions\fR] [\fIpkgname\fR] [\fI\-g group\fR]
.br 
	[\fI\-f <file>\fR|\fI\-fp <pattern>\fR]
.TP 
.B qpkg	\fI\-\-dups\fR	[\fI\-\-slot\fR]
.TP 
.B qpkg	\fI\-\-help\fR
.SH "DESCRIPTION"
qpkg is GenToolKit's "query package" tool, using it, you can find packages owning files on your filesystem, check the integrity of installed packages, and do other queries against installed or uninstalled packages.
.SH "OPTIONS "
.LP 
.I Duplicate Locating:
.LP 
.B \-d, \-\-dups\fR		print packages that have multiple
.br 
				versions installed
.br 
.B \-s, \-\-slot\fR		make \-d SLOT only print dups of the
.br 
				same SLOT
.LP 
.I Package Selection:
.LP 
.B \-f, \-\-find\-file\fR	Finds package that owns file <file>
.br 
.B \-fp, \-\-find\-pattern\fR	Finds to package that owns file
.br 
				matching *<pattern>*
.br 
.B \-I, \-\-installed\fR	Include only installed packages
.br 
.B \-U, \-\-uninstalled\fR	Include only uninstalled packages
.br 
.B \-g, \-\-group\fR		Find by goup (can be combined with
.br 
				other searches)
.LP 
.I Information Selection:
.LP 
.B \-l, \-\-list\fR		List package content
.br 
.B \-i, \-\-info\fR		Get package description and home page.
.br 
.B \-ct, \-\-check\-time
.br 
.B \-tc, \-\-time\-check\fR	Verify package files timestamps
.br 
.B \-cm, \-\-check\-md5
.br 
.B \-mc, \-\-md5\-check\fR	Verify package files md5
.br 
.B \-c, \-\-check\fR		Verify mtimes and md5.
.br 
.B \-q, \-\-query\-deps\fR	display all installed packages 
.br 
\fR				depending on selected packages
.LP 
.I Operation Modifiers:
.LP 
.B \-nc, \-\-no\-color\fR	Don't use colors
.br 
.B \-v, \-\-verbose\fR		Be more verbose [2 levels]
.br 
.B \-vv\fR				Same as \-v \-v
.SH "NOTES"
\fI\-f, \-fp, \-d, \-l, \-ct, \-cm, \fRand \fI\-c\fR apply only to installed packages.
.br 
.TP 
Short options may not be combined on the command\-line, yet.
.TP 
The operation of some flags has been changed in version 1.6 by the stripping of version numbers from some output to see the version numbers play with \fI\-v\fR and \fI\-vv\fR.
.TP 
When using \fI\-f\fR with \fI\-l\fR or \fI\-\-check.. \-v\fR options, only matching files will be displayed, unless \fI\-v\fR is doubled, (yet more verbose), equivalent to \fI\-vv\fR.
.SH "EXAMPLES"
.LP 
.B qpkg \fI\-\-dups\fR		print duplicates oldest first
.br 
.B qpkg \fI\-\-dups \-v\fR..	with versions
.br 
.B qpkg\fR				print list of packages
.br 
.B qpkg\fR porta \fI\-I\fR		print versions of installed portage
.br 
.B qpkg porta \fI\-i\fR		.. + versions in portage tree + 
.br 
				descriptions and homepages
.br 
.B qpkg gawk \fI\-c \-v\fR	check integrity all installed versions 
.br 
				of gawk the older versions will have
.br 
				"damaged" files.
.br 
.B qpkg \fI\-f\fR /bin/ls	print package(s) that own /bin/ls
.SH "AUTHORS"
Vitaly Kushneriuk <vitaly@gentoo.org>, 2002: qpkg
.br 
Karl Trygve Kalleberg <karltk@gentoo.org>, 2002: man page
.br 
Brandon Low <lostlogic@gentoo.org>, 2002: maintainance
.SH "SEE ALSO"
ebuild(5) 
.TP 
The \fI/usr/sbin/qpkg\fR script. 
.TP 
