# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

include ../../makedefs.mak

.PHONY: all

all:

dist:
	mkdir -p ../../$(DISTDIR)/src/<TOOL>/
	cp Makefile <TOOL> <TOOL>.1 ../../$(DISTDIR)/src/<TOOL>/

install: all
	install -m 0755 <TOOL> $(BINDIR)/
	install -m 0644 <TOOL>.1 $(MAN1DIR)/

