.TH "etcat" "1" "0.1.4" "Alastair Tse <liquidx@gentoo.org>" "Gentoo Administration"
.SH "NAME"
.LP 
etcat \- Gentoo Portage Information Extractor
.SH "SYNTAX"
.LP 
etcat [\fIoption\fP|command] <\fIquery|package\fP>

.SH "DESCRIPTION"
.LP 
etcat tries to complement the existing portage related tools but geared specifically for the power user. It enables users and developers to quickly find out information on particular packages without resorting to manually poking the portage tree and portage database.

.LP 
More specifically, it lists the versions available highlighted by their status (stable/testing/masked/install) for a package, lists use flags per package with descriptions, calculates the installed size of a package and also outputs the relevent entries in the changelog related to the package version.

.LP 
It also employes a smarter package query syntax than emerge where examples such as:
.LP .IP 
mozilla\-1.1
.br 
mozilla\-1.*
.LP 
are accepted.

.SH "OPTIONS"
.LP 
\fB\-b\fR <\fI/path/to/file\fR> [\fIcategory\fR]
.br 
\fBbelongs\fR <\fI/path/to/file\fR> [\fIcategory\fR]
.IP 
Searches for the package which a file belongs to with an option to restrict a search to a single or multiple category. Wildcards in the category name is accepted to speed up searching. (eg. etcat belongs /usr/lib/libmpeg.so "media\-*")

.LP 
\fB\-c\fR <\fIpackage[\-version]\fR>
.br 
\fBchanges\fR <\fIpackage[\-version]\fR>
.IP 
Outputs ChangeLog entry for the package and version specified. Uses the latest package version if none specified.

.LP 
\fB\-d\fR <\fIregex expression\fR>
.br 
\fBdepends\fR <\fIregex expression\fR>
.IP 
Searches through portage for a dependency string satisfying that regular expression.

.LP 
\fB\-f\fR <\fIpackage[\-version]\fR>
.br 
\fBfiles\fR <\fIpackage[\-version]\fR>
.IP 
Lists all the files installed for this package.

.LP 
\fB\-s\fR <\fIpackage\fR>
.br 
\fBsize\fR <\fIpackage\fR>
.IP 
Outputs the installed size of the package.

.LP 
\fB\-u\fR <\fIpackage[\-version]\fR>
.br 
\fBuses\fR <\fIpackage[\-version]\fR>
.IP 
Outputs the USE flags supported by this package and also their installed state and description.

.LP 
\fB\-v\fR <\fIpackage\fR>
.br 
\fBversions\fR <\fIpackage\fR>
.IP 
Output all the versions for packages that match the \fIpackage\fR name given with indication of whether the packages is stable, masked, unstable or installed.
.SH "SEE ALSO"
.LP 
Type \fBetcat\fR for examples and more information
.SH "AUTHORS"
.LP 
Alastair Tse <liquidx@gentoo.org>
