.TH "eread" "1" "1.0" "Donnie Berkholz" "gentoolkit"
.SH "NAME"
.LP 
eread \- Gentoo: Tool to display and manage ELOG files from portage
.SH "SYNTAX"
.LP 
eread
.SH "DESCRIPTION"
.LP 
This tool is used to display and manage ELOG files produced by portage version 2.1 and higher.
.SH "ENVIRONMENT VARIABLES"
The eread utility uses the PAGER environment variable to display the ELOG files. If the variable is not set, it defaults to /usr/bin/less.
