.TH mkebuild "1" "Nov 2003" "gentoolkit"
.SH NAME
mkebuild \- Gentoo: Interactive ebuild generator
.SH SYNOPSIS
.B mkebuild
.SH BUGS
This tool is obsolete, as of gentoolkit 0.2.0.  
Use ebuilder [app\-portage/ebuilder] instead.
.SH SEE ALSO
.BR ebuilder(1)
.br
.BR /usr/sbin/ebuilder
.br
.BR /usr/sbin/mkebuild

.SH AUTHORS
This informative man page was written by Karl Trygve Kalleberg 
<karltk@gentoo.org> and expanded by Katerina Barone\-Adesi 
<katerinab@gmail.com>.

