.TH equery "1" "Jan 2004" "gentoolkit"
.SH NAME
equery \- Gentoo: Package Query Tool
.SH SYNOPSIS
.B equery
.SH BUGS
This tool does not yet have a man page. Feel free to submit a bug about it to
http://bugs.gentoo.org
.SH AUTHORS
This informative man page was written by Karl Trygve Kalleberg 
<karltk@gentoo.org>.

