.TH ewhich 1 "October 19, 2003" "ewhich"

.SH NAME
ewhich \- Gentoo: program for resolving ebuild names

.SH SYNOPSIS
.B ewhich
[ -h | --help ] <package>

.SH DESCRIPTION
.B ewhich
is a little tool to find the actual ebuild file for a given package name.
It can use simple package names (like xfree), package names with category
(like x11-base/xfree) or DEPEND atoms (like >=x11-base/xfree-4.3.0).

.SH BUGS
.B ewhich
No known bugs

.SH SEE ALSO
emerge(1), make.conf(5), ebuild(5)

.SH AUTHOR
Marius Mauch <genone@gentoo.org>
