.TH "eshowkw" "1" "Ciaran McCreesh" "gentoolkit-dev"
.SH "NAME"
.LP 
eshowkw \- Displays ebuild keywords in a graphical form.
.SH "SYNTAX"
.LP 
eshowkw [ packagename ] (defaults to current directory if no packagename is provided)


.SH "AUTHORS"
.LP 
Ciaran McCreesh <ciaranm@gentoo.org>
Mart Raudsepp <leio@gentoo.org>
Christian Ruppert <idl0r@gentoo.org>
.SH "BUGS"
Please report any bugs to http://bugs.gentoo.org
