.TH gentool-package-count "1" "Nov 2002" "gentoolkit"
.SH NAME
gentool-package-count\- Counts the number of packages available in the tree.
.SH SYNOPSIS
.B gentool-package-revision 
.SH DESCRIPTION
The \fBgentool-package-count\fR utility counts the number of packages
available for installation in your local Portage tree. It will inform of
total package count, total category count, and total unique packages. It 
is completely useless.
.SH AUTHOR
Karl Trygve Kalleberg <karltk@gentoo.org>, 2002
.SH SEE ALSO
gentool-package-size(1)
.TP
See \fI/usr/share/doc/gentoolkit-<version>/\fR for documentation on other gentoolkit utilities.

