#!/bin/sh
# Copyright 2002-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header$
# Author: Karl Trygve Kalleberg <karltk@gentoo.org>

if [ ! -f $HOME/.gentoo/gentool-env ] ; then
	echo "You must make a $HOME/.gentoo/gentool-env file that contains"
	echo "AUTHORNAME=\"Your name\""
	echo "AUTHOREMAIL=\"Your @gentoo.org mail address\""
fi

. $HOME/.gentoo/gentool-env

dn="`dirname $1`"
bn="`basename $1`"
ebuild=`echo $bn | sed "s/\.ebuild//"`

ver=`echo $ebuild | sed "s/\(.*\)-\([0-9].*\)/\2/"`
name=`echo $ebuild | sed "s/\(.*\)-\([0-9].*\)/\1/"`
rev=`echo $ver | grep "\-r[0-9]*" | sed "s/.*-r\([0-9]*\)/\1/"`
basever=`echo $ver | sed "s/-r[0-9]*//"`

oldver=$ebuild
newver=""
if [ -z "$rev" ] ; then 
	newver=${ebuild}-r1
else 
	newrev=$[rev + 1]
	newver=${name}-${basever}-r${newrev}
fi

echo "# Directory   : $dn"
echo "# Old version : $oldver"
echo "# New version : $newver"
echo

cd ${dn}

echo "Updating revisions for ebuilds digests"
mv ${oldver}.ebuild ${newver}.ebuild
mv files/digest-${oldver} files/digest-${newver}

#echo "Removing old revisions from CVS"
#cvs remove -f ${oldver}.ebuild
#cvs remove -f files/digest-${oldver}

echo "Adding new revisions to CVS"
cvs add ${newver}.ebuild
cvs add files/digest-${newver}

if [ ! -f ChangeLog ] ; then
	echo "!!! Cannot fix ChangeLog, does not exist" > /dev/stderr
	exit -1
fi

echo "Adding new entry in ChangeLog"

lns=`cat ChangeLog | wc -l | tr -d ' '`
mv ChangeLog ChangeLog.orig
(head -n 3 ChangeLog.orig ; 
	echo ""
	echo "*$newver (`date +\"%d %b %Y\"`)" ;
	echo "" ;
	echo "  `date +\"%d %b %Y\"`; $AUTHORNAME <$AUTHOREMAIL> ${newver}.ebuild files/digest-${newver}:" ;
	echo "" ;
	echo "  # INSERT COMMENT HERE" ;
	echo "" ;
	echo "  Removed ${oldver}.ebuild files/digest-${oldver}" ;
	echo "" ; 
	tail -n $[lns-4] ChangeLog.orig
) > ChangeLog
