.TH gentool-package-size "1" "Nov 2002" "gentoolkit"
.SH NAME
gentool-package-size \- Calculates the diskspace occupied by a package
.SH SYNOPSIS
.B gentool-package-revision 
\fIpackage-name\fR
.SH DESCRIPTION
The \fBgentool-package-revision\fR utility calculates the actual diskspace
taken by a given package. It will not consider the parition block size. The 
package name need not be absolute, the closest match is sought.
.SH EXAMPLE
.LP
To look for the first package with a name starting with \fImozilla\fR:
.RS
.nf
\fBgentool-package-revision mozilla\fP
.fi
.RE

.LP
To look for the first package in category \fInet-www\fR starting with
\fImozilla\fR:
.RS
.nf
\fBgentool-package-revision net-www/mozilla\fP
.fi
.RE

.LP
To only match a very specific version of \fImozilla\fR in the
\fInet-www\fR category:
.RS
.nf
\fBgentool-package-revision net-www/mozilla-1.0.1-r3\fP
.fi
.RE

.SH AUTHOR
Karl Trygve Kalleberg <karltk@gentoo.org>, 2002
.SH SEE ALSO
gentool-package-count(1)
.TP
See \fI/usr/share/doc/gentoolkit-<version>/\fR for documentation on other gentoolkit utilities.

