.TH gentool-bump-revision "1" "Nov 2002" "gentoolkit"
.SH NAME
gentool-bump-revision \- Bumps the revision number of a given package
.SH SYNOPSIS
.B gentool-bump-revision 
\fIebuild\fR
.SH DESCRIPTION
The \fBgentool-bump-revision\fR utility bumps the revision of an existing
ebuild in the Portage tree. It does this by copying the specified ebuild
file to a new filename with an increased revision number. It takes care 
of the digest file, adding both to CVS, and it also adds an entry in the 
ChangeLog for you to fill in. After the revision bump, should always make
certain any auxiliary files like scripts, etc, are installed properly.
.SH AUTHOR
Karl Trygve Kalleberg <karltk@gentoo.org>, 2002
.SH SEE ALSO
change(1)
.TP
See \fI/usr/share/doc/gentoolkit-<version>/\fR for documentation on other gentoolkit utilities.

